### ISSUE TITLE
Connection Management Best Practices

### ISSUE THREAD

**Issue by FraserHamilton** [deno-postgres/deno-postgres#147]
What are the best practices for managing our connections to the database? I'm unsure of how to manage these properly and the readme doesn't really provide much guidance on this. Currently I'm opening a connection, executing my query and then closing the connection. Is there a recommended way to handle eliminating this code duplication?

**Comment by ebebbington** [comment]
Hi @FraserHamilton , see here: https://github.com/deno-postgres/deno-postgres/pull/150
