### ISSUE TITLE
URL is not assignable to parameter of type 'string'

### ISSUE THREAD

**Issue by yababay** [deno-postgres/deno-postgres#153]
Hi, deno-postgres.

I have used this driver sucessfully for some weeks, but after updating I have discovered an error:

```
TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.51.0/path/posix.ts:433:18
```
It appears on my computer even in very simple code:
```
import { Client } from "https://deno.land/x/postgres/mod.ts";

async function main() {
  const client = new Client({
    user: "me",
    database: "some",
    hostname: "localhost",
    password: "qwerty",
    port: 5432
  });
  await client.connect();
  const result = await client.query("SELECT * FROM users;");
  console.log(result.rows);
  await client.end();
}
```
How can I fix this? Thank You!

**Comment by bartlomieju** [comment]
Type definition for `URL` constructor has been changed in `1.2.0` to align with TypeScript type definitions. We need to update `deps.ts` to use latest version of `std/`. Meanwhile you can downgrade Deno to `1.1.3` and it should still work.

**Comment by yababay** [comment]
Thank you for quick response!
