### ISSUE TITLE
deno-postgres@v0.4.4 seems not to be published in deno's module registry

### ISSUE THREAD

**Issue by uki00a** [deno-postgres/deno-postgres#169]
## Description
Importing deno-postgres@v0.4.4 returns 404 error:
```shell
Download https://deno.land/x/postgres@v0.4.4/mod.ts
error: Import 'https://deno.land/x/postgres@v0.4.4/mod.ts' failed: 404 Not Found
```
## Possible cause & solution
I think this problem is due to [the recent changes in the registry](https://deno.land/posts/registry2#changes). This problem can be solved by setting up a webhook in this repository.
## Ref
- https://deno.land/posts/registry2
- https://deno.land/images/add_webhook.mp4

**Comment by pandakub** [comment]
Seconded.

This is causing an error that forces me to revert to 1.3.0 of Deno.

0.4.3 has a TypeScript error in connection.ts that 0.4.4 resolves, so this is pretty dire

**Comment by PaulFish-Radius** [comment]
Please let us know when resolved - thanks for the update and great library.

**Comment by PaulFish-Radius** [comment]
@hayd deno is now onto v1.4.0 - may we have an update, when available?

**Comment by Zerowalker** [comment]
waiting for this as well, using the "raw" link as a workaround but best would be if it's going through the right place:)

**Comment by hayd** [comment]
I think this should be fixed now, and will work for future versions. Apologies!

**Comment by PaulFish-Radius** [comment]
Thank you @hayd for all the contributions you make to the deno community - it means a lot.

**Comment by uki00a** [comment]
Thanks for resolving this @hayd!
