### ISSUE TITLE
Update for deno 1.4.0

### ISSUE THREAD

**Issue by PaulFish-Radius** [deno-postgres/deno-postgres#174]
Deno is moving fast and breaking things. 

Getting errors with postgres@v0.4.4 on deno 1.4.0 

Errors below (sorry for formatting):

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Deferred,
  ~~~~~~~~
    at https://deno.land/x/postgres@v0.4.4/deps.ts:7:3

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { RowDescription, Column, Format } from "./connection.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.4/query.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Message } from "./connection.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.4/error.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { ConnectionParams } from "./connection_params.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.4/connection.ts:35:1

**Comment by hayd** [comment]
Could you make a PR? Otherwise I will fix this tonight.

Should be `import type { ConnectionParams } from "./connection_params.ts";` etc. and also READMEs.
