### ISSUE TITLE
Add TODOs Badge

### ISSUE THREAD

**Issue by patrickdevivo** [deno-postgres/deno-postgres#86]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `// TODO` comments are in this codebase:

[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/buildondata/deno-postgres)](https://www.tickgit.com/browse?repo=github.com/buildondata/deno-postgres)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/buildondata/deno-postgres)](https://www.tickgit.com/browse?repo=github.com/buildondata/deno-postgres)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

**Comment by hayd** [comment]
I think will close this for now, but may turn this on in the future.
Interesting project!
