### ISSUE TITLE
Don't know how to parse column type: 1042

### ISSUE THREAD

**Issue by jakajancar** [deno-postgres/deno-postgres#99]
When selecting from `char(n)` column.

**Comment by jakajancar** [comment]
And sometimes I get
```
Error: Unexpected frame: D
    at Connection._simpleQuery (connection.ts:309:15)
    at async Connection.query (connection.ts:530:14)
    at async Client.query (client.ts:24:12)
```
if I try to select it without casting to test. Hmm.

**Comment by qimingweng** [comment]
There should probably be a system to add parsing for unknown column types like in node-postgres.

CITEXT (oid 20180) is also unknown, and throwing an error of this level means this library will be useless for any serious postgres distribution.

**Comment by bartlomieju** [comment]
@jakajancar @qimingweng sorry for being silent. I'm open to expanding the list of supported types as well as adding way to parse unknown columns.

**Comment by qimingweng** [comment]
@bartlomieju all good– Deno 1.0 is exciting stuff. Will be interesting to see where the community goes from here.

**Comment by bander-saeed94** [comment]
Hi there, Any update regarding this issue?

**Comment by bander-saeed94** [comment]
This raise when inserting as well when selecting
